name: Github Pages Deploy

on:
  push:
    branches:
    - "main"

jobs:
  build:
    runs-on: Windows 10 Pro

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: build
      run: npm install && npm run build

    - name: Test
      uses: npm run test

    - name: Deploy
    run:
    git config --global user.name 'AliHamza2317'  
    git config --global user.email 'alihamza707580@gmail.com'  
    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
    npm run deploy
